package discordhx.gateway.events;


enum abstract GatewayEventTypes(String) from String to String {
    var READY = "READY";
    var RESUMED = "RESUMED";
    var GUILD_CREATE = "GUILD_CREATE";
    var GUILD_UPDATE = "GUILD_UPDATE";
    var GUILD_DELETE = "GUILD_DELETE";
    var GUILD_BAN_ADD = "GUILD_BAN_ADD";
    var GUILD_BAN_REMOVE = "GUILD_BAN_REMOVE";
    var GUILD_EMOJIS_UPDATE = "GUILD_EMOJIS_UPDATE";
    var GUILD_INTEGRATIONS_UPDATE = "GUILD_INTEGRATIONS_UPDATE";
    var GUILD_MEMBER_ADD = "GUILD_MEMBER_ADD";
    var GUILD_MEMBER_REMOVE = "GUILD_MEMBER_REMOVE";
    var GUILD_MEMBER_UPDATE = "GUILD_MEMBER_UPDATE";
    var GUILD_MEMBERS_CHUNK = "GUILD_MEMBERS_CHUNK";
    var GUILD_ROLE_CREATE = "GUILD_ROLE_CREATE";
    var GUILD_ROLE_UPDATE = "GUILD_ROLE_UPDATE";
    var GUILD_ROLE_DELETE = "GUILD_ROLE_DELETE";
    var MESSAGE_CREATE = "MESSAGE_CREATE";
    var MESSAGE_UPDATE = "MESSAGE_UPDATE";
    var MESSAGE_DELETE = "MESSAGE_DELETE";
    var MESSAGE_DELETE_BULK = "MESSAGE_DELETE_BULK";
    var MESSAGE_REACTION_ADD = "MESSAGE_REACTION_ADD";
    var MESSAGE_REACTION_REMOVE = "MESSAGE_REACTION_REMOVE";
    var MESSAGE_REACTION_REMOVE_ALL = "MESSAGE_REACTION_REMOVE_ALL";
    var MESSAGE_REACTION_REMOVE_EMOJI = "MESSAGE_REACTION_REMOVE_EMOJI";
    var PRESENCE_UPDATE = "PRESENCE_UPDATE";
    var TYPING_START = "TYPING_START";
    var USER_UPDATE = "USER_UPDATE";
    var VOICE_STATE_UPDATE = "VOICE_STATE_UPDATE";
    var VOICE_SERVER_UPDATE = "VOICE_SERVER_UPDATE";
    var WEBHOOKS_UPDATE = "WEBHOOKS_UPDATE";
}